### ISSUE TITLE
Total Expenses displays wrong value when has a baby

### ISSUE THREAD

**Issue by pybotlad** [leanhduy/cashflow#37]
- Original Total Expenses: -3052$
Has a baby with expense 250$ with

Actual Results: Total Expenses displays -3552$
Expected Results: Total Expenses displays -3302$

![image](https://github.com/user-attachments/assets/6efa4c67-59ca-49f8-a1c8-7c4d74de52fa)

**Comment by leanhduy** [comment]
**Root cause**
- Incorrect calculation logic in the `getTotalExpensesAmount` method, the `expenses` array already includes the child expenses, so the `data.childNum * data.expensesPerChild` causing extra expenses is added to the total expenses amount
```javascript
export const getTotalExpenseAmount = (data) => {
  return (
    data.expenses.reduce((total, expense) => total + expense.amount, 0) +
    data.childNum * data.expensePerChild
  )
}
```
**Solution**
- remove the extra part `data.childNum * data.expensesPerChild` in the formula.
