### ISSUE TITLE
Assests table does not displays stock after selling

### ISSUE THREAD

**Issue by pybotlad** [leanhduy/cashflow#38]
Precondition: Assests table has 2500 Stock - MYT4U cost 1$
Sell 2000 stock

Actual: Assests table does not displays 500 Stock - MYT4U cost 1$
Expected: Assests table displays 500 Stock - MYT4U cost 1$

Before
![1](https://github.com/user-attachments/assets/a8ce7898-8b44-4d6b-8a65-7ec5aeb995fa)
After
![3](https://github.com/user-attachments/assets/207e9689-b96e-46cf-a157-f21f19eea319)

**Comment by leanhduy** [comment]
This not a bug because the form with input is NOT for selling, it is for BUYING more stocks.
At this moment of the game, there is no option to sell a certain amount of stock you owns. When you sell, it means you sell all of your stocks. 
Nevertheless, this is can be seen as a bad UX design, which make the user confuses about the functionality of the game.
Create a separated issue to address this at:

**Comment by leanhduy** [comment]
A new issue is created to address bad UX at [Issue-43](https://github.com/leanhduy/cashflow/issues/43)
Since it's not a bug, this issue is closed without any further actions.
